export const ALL_ANALYSIS_REQUEST = "ALL_ANALYSIS_REQUEST";
export const ALL_ANALYSIS_SUCCESS = "ALL_ANALYSIS_SUCCESS";
export const ALL_ANALYSIS_FAIL = "ALL_ANALYSIS_FAIL";

export const ADMIN_ANALYSIS_REQUEST = "ADMIN_ANALYSIS_REQUEST";
export const ADMIN_ANALYSIS_SUCCESS = "ADMIN_ANALYSIS_SUCCESS";
export const ADMIN_ANALYSIS_FAIL = "ADMIN_ANALYSIS_FAIL";

export const NEW_ANALYSIS_REQUEST = "NEW_ANALYSIS_REQUEST";
export const NEW_ANALYSIS_SUCCESS = "NEW_ANALYSIS_SUCCESS";
export const NEW_ANALYSIS_FAIL = "NEW_ANALYSIS_FAIL";

export const UPDATE_ANALYSIS_REQUEST = "UPDATE_ANALYSIS_REQUEST";
export const UPDATE_ANALYSIS_SUCCESS = "UPDATE_ANALYSIS_SUCCESS";
export const UPDATE_ANALYSIS_RESET = "UPDATE_ANALYSIS_RESET";
export const UPDATE_ANALYSIS_FAIL = "UPDATE_ANALYSIS_FAIL";

export const DELETE_ANALYSIS_REQUEST = "DELETE_ANALYSIS_REQUEST";
export const DELETE_ANALYSIS_SUCCESS = "DELETE_ANALYSIS_SUCCESS";
export const DELETE_ANALYSIS_RESET = "DELETE_ANALYSIS_RESET";
export const DELETE_ANALYSIS_FAIL = "DELETE_ANALYSIS_FAIL";

// export const PRODUCT_DETAILS_REQUEST = "PRODUCT_DETAILS_REQUEST";
// export const PRODUCT_DETAILS_SUCCESS = "PRODUCT_DETAILS_SUCCESS";
// export const PRODUCT_DETAILS_FAIL = "PRODUCT_DETAILS_FAIL";

export const CLEAR_ERRORS = "CLEAR_ERRORS";