export const MY_SAMPLE_REQUEST = "MY_SAMPLE_REQUEST";
export const MY_SAMPLE_SUCCESS = "MY_SAMPLE_SUCCESS";
export const MY_SAMPLE_FAIL = "MY_SAMPLE_FAIL";

export const CLEAR_ERRORS = "CLEAR_ERRORS";