export const MY_SAMPLE_REQUEST = "MY_SAMPLE_REQUEST";
export const MY_SAMPLE_SUCCESS = "MY_SAMPLE_SUCCESS";
export const MY_SAMPLE_FAIL = "MY_SAMPLE_FAIL";

export const MY_SAMPLE_RESULT_REQUEST = "MY_SAMPLE_RESULT_REQUEST";
export const MY_SAMPLE_RESULT_SUCCESS = "MY_SAMPLE_RESULT_SUCCESS";
export const MY_SAMPLE_RESULT_FAIL = "MY_SAMPLE_RESULT_FAIL";

export const SAMPLE_SUBMIT_REQUEST = "SAMPLE_SUBMIT_REQUEST"
export const SAMPLE_SUBMIT_SUCCESS = "SAMPLE_SUBMIT_SUCCESS"
export const SAMPLE_SUBMIT_FAIL = "SAMPLE_SUBMIT_FAIL"

export const CLEAR_ERRORS = "CLEAR_ERRORS";