export const ALL_PACKAGE_REQUEST = "ALL_PACKAGE_REQUEST";
export const ALL_PACKAGE_SUCCESS = "ALL_PACKAGE_SUCCESS";
export const ALL_PACKAGE_FAIL = "ALL_PACKAGE_FAIL";

export const ADMIN_PACKAGE_REQUEST = "ADMIN_PACKAGE_REQUEST";
export const ADMIN_PACKAGE_SUCCESS = "ADMIN_PACKAGE_SUCCESS";
export const ADMIN_PACKAGE_FAIL = "ADMIN_PACKAGE_FAIL";

export const NEW_PACKAGE_REQUEST = "NEW_PACKAGE_REQUEST";
export const NEW_PACKAGE_SUCCESS = "NEW_PACKAGE_SUCCESS";
export const NEW_PACKAGE_FAIL = "NEW_PACKAGE_FAIL";

export const UPDATE_PACKAGE_REQUEST = "UPDATE_PACKAGE_REQUEST";
export const UPDATE_PACKAGE_SUCCESS = "UPDATE_PACKAGE_SUCCESS";
export const UPDATE_PACKAGE_RESET = "UPDATE_PACKAGE_RESET";
export const UPDATE_PACKAGE_FAIL = "UPDATE_PACKAGE_FAIL";

export const DELETE_PACKAGE_REQUEST = "DELETE_PACKAGE_REQUEST";
export const DELETE_PACKAGE_SUCCESS = "DELETE_PACKAGE_SUCCESS";
export const DELETE_PACKAGE_RESET = "DELETE_PACKAGE_RESET";
export const DELETE_PACKAGE_FAIL = "DELETE_PACKAGE_FAIL";

export const CLEAR_ERRORS = "CLEAR_ERRORS";